import { CadetTaskItem } from "../types/cadetTraining";

export const DEFAULT_CADET_TASKS: CadetTaskItem[] = [
  // --- PHASE 1: BOSUN ASSIST (Months 1–3) ---
  {
    id: "cadet-task-p1-001",
    phase: "bosun_assist",
    title: "Mooring Winches & Line Handling at Port Departure",
    description: "Participated in forward mooring station operations during unmooring from Berth No. 4. Monitored spring line and head line slack, observed snap-back danger corridors, and assisted with dogging winch brakes.",
    assistDescription: "Assisted Bosun in flaking out 64mm polypropylene mooring hawsers on the forecastle, operating hydraulic fairlead rollers, and securing heaving lines in rope racks.",
    date: "2026-05-12",
    status: "Approved by Officer",
    documentationName: "Mooring_Station_Forward_Inspection.jpg",
    documentationType: "image",
    documentationUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
    officerMentor: "Bosun & C/O",
    officerRemarks: "Cadet demonstrated strict situational awareness regarding snap-back danger zones. Excellent rope coiling technique.",
    trbReference: "STCW II/1 - Task 1.1: Mooring Systems",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 4,
    location: "Forecastle Mooring Deck",
    createdAt: "2026-05-12T08:30:00Z",
    updatedAt: "2026-05-12T14:15:00Z"
  },
  {
    id: "cadet-task-p1-002",
    phase: "bosun_assist",
    title: "Main Deck Hatch Coaming Preservation & Painting",
    description: "Executed mechanical rust descaling using pneumatic needlegun on Cargo Hold No. 3 hatch coaming corners. Degreased exposed metal with solvent and applied zinc-rich primer followed by marine polyurethane topcoat.",
    assistDescription: "Assisted Able Seafarer and Bosun with air compressor line rigging, moisture trap draining, and chemical safety data sheet (MSDS) paint ratio mixing.",
    date: "2026-05-20",
    status: "Approved by Officer",
    documentationName: "Coaming_Coating_DFT_Test.pdf",
    documentationType: "document",
    documentationUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80",
    officerMentor: "Bosun",
    officerRemarks: "Needlegun angle well maintained; no gouging of steel substrate. Paint thickness dry film thickness (DFT) verified at 120 microns.",
    trbReference: "STCW II/1 - Task 1.4: Surface Maintenance",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 5,
    location: "Main Deck Hatch No. 3",
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-20T16:00:00Z"
  },
  {
    id: "cadet-task-p1-003",
    phase: "bosun_assist",
    title: "Windlass Brake Lining Inspection & Anchor Wash Testing",
    description: "Inspected port and starboard anchor windlass friction band linings for wear. Tested sea chest pressurized anchor wash nozzles and inspected chain locker bitter end release pins.",
    assistDescription: "Assisted Bosun in applying heavy open gear lithium grease to windlass reduction gears and greasing universal grease nipples with manual lever grease gun.",
    date: "2026-06-04",
    status: "Completed",
    documentationName: "Windlass_Grease_Lining_Check.jpg",
    documentationType: "image",
    documentationUrl: "https://images.unsplash.com/photo-1505705694340-019e1e335916?auto=format&fit=crop&w=600&q=80",
    officerMentor: "Bosun",
    officerRemarks: "Lining clearance 8.2mm, well within tolerance. Bitter end quick-release hammer pin inspected.",
    trbReference: "STCW II/1 - Task 1.2: Ground Tackle",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 3.5,
    location: "Forward Windlass Platform",
    createdAt: "2026-06-04T10:15:00Z",
    updatedAt: "2026-06-04T15:30:00Z"
  },

  // --- PHASE 2: 3RD OFFICER ASSIST (Months 4–6) ---
  {
    id: "cadet-task-p2-001",
    phase: "third_officer_assist",
    title: "Weekly Lifeboat Engine Run & Hydrostatic Release Inspection",
    description: "Conducted weekly SOLAS inspection of Port & Starboard totally enclosed motor lifeboats. Verified lifeboat engine forward/reverse gearbox engagement, rudder quadrant freedom, and emergency sprinkler pump operation.",
    assistDescription: "Assisted 3rd Officer with checking hydrostatic release units (HRU) on Hammar liferaft racks, inspecting hydrostatic expiration stamps, and recording lifeboat compass deviation.",
    date: "2026-07-08",
    status: "Approved by Officer",
    documentationName: "LSA_Weekly_Checklist_Signed.pdf",
    documentationType: "checklist",
    documentationUrl: "https://images.unsplash.com/photo-1584466977773-e625c37cdd50?auto=format&fit=crop&w=600&q=80",
    officerMentor: "3rd Officer (Ship Safety Officer)",
    officerRemarks: "Cadet accurately followed SOLAS Reg III/20 checklist. Demonstrated correct understanding of on-load / off-load release hook interlocks.",
    trbReference: "STCW II/1 - Task 2.1: Life-Saving Appliances",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 4,
    location: "Boat Deck Port & Stbd",
    createdAt: "2026-07-08T09:30:00Z",
    updatedAt: "2026-07-08T14:45:00Z"
  },
  {
    id: "cadet-task-p2-002",
    phase: "third_officer_assist",
    title: "FFA Portable Fire Extinguishers & SCBA Set Monthly Audit",
    description: "Inspected 38 portable fire extinguishers across Accommodation, Bridge, and Galley. Verified pressure gauges in green zone, checked inspection tags, weighed CO2 cartridges, and inverted foam/dry powder cylinders.",
    assistDescription: "Assisted 3rd Officer in testing Dräger SCBA breathing apparatus sets: face mask low-pressure leak test, audible whistle alarm warning at 55 bar, and cylinder hydrostatic test dates.",
    date: "2026-07-22",
    status: "Completed",
    documentationName: "FFA_Audit_Accommodation_Deck.jpg",
    documentationType: "image",
    documentationUrl: "https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?auto=format&fit=crop&w=600&q=80",
    officerMentor: "3rd Officer",
    officerRemarks: "All extinguishers tagged and recorded in SMS Safety Database. Defective safety pin on Galley CO2 unit replaced immediately.",
    trbReference: "STCW II/1 - Task 2.3: Firefighting Appliances",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 4.5,
    location: "Accommodation Decks A-D & Bridge",
    createdAt: "2026-07-22T08:00:00Z",
    updatedAt: "2026-07-22T13:30:00Z"
  },
  {
    id: "cadet-task-p2-003",
    phase: "third_officer_assist",
    title: "Bridge Pyrotechnics Inventory & Line-Throwing Apparatus Verification",
    description: "Inspected bridge emergency distress pyrotechnic locker. Checked 12 rocket parachute flares, 4 red hand flares, 2 buoyant orange smoke signals, and 4 bridge wing MOB smoke/light marker units.",
    assistDescription: "Assisted 3rd Officer with verifying propellant shelf-life dates, checking watertight rubber seals on containment container, and updating SOLAS Pyrotechnics Register.",
    date: "2026-08-11",
    status: "In Progress",
    documentationName: "Pyrotechnics_Locker_Check.pdf",
    documentationType: "document",
    officerMentor: "3rd Officer",
    officerRemarks: "All pyrotechnics valid until Q3 2028. Rocket flares safely restowed in dedicated watertight casing.",
    trbReference: "STCW II/1 - Task 2.5: Pyrotechnics & Distress Signals",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 2,
    location: "Navigation Bridge Pyrotechnics Locker",
    createdAt: "2026-08-11T11:00:00Z",
    updatedAt: "2026-08-11T12:30:00Z"
  },

  // --- PHASE 3: 2ND OFFICER ASSIST (Months 7–9) ---
  {
    id: "cadet-task-p3-001",
    phase: "second_officer_assist",
    title: "Weekly ECDIS ENC Chart Updates & Notice to Mariners",
    description: "Loaded Admiralty Vector Chart Service (AVCS) Base/Update DVDs into Transas Navi-Sailor 4000 ECDIS. Verified installation of 142 Electronic Navigational Chart (ENC) updates along Malacca Strait and Singapore Strait passages.",
    assistDescription: "Assisted 2nd Officer in plotting Temporary & Preliminary (T&P) Notices, reviewing Admiralty Notices to Mariners (ANM) Week 34, and applying manual chart corrections to paper backup chart BA 3833.",
    date: "2026-08-28",
    status: "Approved by Officer",
    documentationName: "ECDIS_ENC_Update_Log_W34.png",
    documentationType: "image",
    documentationUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    officerMentor: "2nd Officer (Navigating Officer)",
    officerRemarks: "Cadet proficient in ECDIS chart loading workflow and manual symbol plotting on paper backup. Log signed.",
    trbReference: "STCW II/1 - Task 3.1: Chart Corrections & ECDIS",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 4,
    location: "Navigation Bridge Chart Table",
    createdAt: "2026-08-28T14:00:00Z",
    updatedAt: "2026-08-28T18:30:00Z"
  },
  {
    id: "cadet-task-p3-002",
    phase: "second_officer_assist",
    title: "Passage Plan Preparation & Under-Keel Clearance (UKC) Calculations",
    description: "Assisted in calculating waypoint coordinates, cross-track limits (XTL), safety depth contours, and wheel-over positions for approaching Tokyo Bay Traffic Separation Scheme (TSS).",
    assistDescription: "Assisted 2nd Officer with dynamic squat calculations at 12 knots in shallow waters, verifying minimum company gross UKC margin of 10% draft.",
    date: "2026-09-15",
    status: "Completed",
    documentationName: "Tokyo_Bay_Passage_Plan_Annex.pdf",
    documentationType: "document",
    officerMentor: "2nd Officer",
    officerRemarks: "Thorough calculation of tidal heights and water density adjustments for brackish estuary.",
    trbReference: "STCW II/1 - Task 3.2: Passage Planning",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 5,
    location: "Bridge Voyage Planning Station",
    createdAt: "2026-09-15T09:00:00Z",
    updatedAt: "2026-09-15T16:00:00Z"
  },
  {
    id: "cadet-task-p3-003",
    phase: "second_officer_assist",
    title: "Bridge Watchkeeping Assistant & ARPA Radar Target Plotting",
    description: "Stood active 00:00–04:00 middle watch alongside 2nd Officer. Maintained strict visual and acoustic lookout, plotted 8 intersecting target vessels on X-band radar using automatic radar plotting aids (ARPA).",
    assistDescription: "Assisted 2nd Officer with CPA/TCPA collision avoidance calculations, logging weather telemetry (barometric pressure, wind force, sea state), and calling out navigational buoys.",
    date: "2026-09-29",
    status: "In Progress",
    documentationName: "ARPA_Radar_Plot_Watch_Log.jpg",
    documentationType: "image",
    documentationUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    officerMentor: "2nd Officer",
    officerRemarks: "Maintained diligent look-out. Correctly identified masthead and sidelight configurations of passing container ship.",
    trbReference: "STCW II/1 - Task 3.4: Bridge Watchkeeping Standards",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 4,
    location: "Navigation Bridge Console",
    createdAt: "2026-09-29T00:30:00Z",
    updatedAt: "2026-09-29T04:15:00Z"
  },

  // --- PHASE 4: CHIEF OFFICER ASSIST (Months 10–12) ---
  {
    id: "cadet-task-p4-001",
    phase: "chief_officer_assist",
    title: "Draft Survey & Loading Computer Bending Moment Calculations",
    description: "Conducted arrival draft survey in port. Read draft marks forward, midships port/starboard, and aft using pilot ladder. Computed mean draft, true trim, and water density hydrometer correction to verify cargo quantity onboard.",
    assistDescription: "Assisted Chief Officer in inputting cargo stowage weights into the approved vessel loading computer, verifying Shearing Forces (SF) and Bending Moments (BM) within 78% of maximum seagoing limits.",
    date: "2026-10-01",
    status: "Approved by Officer",
    documentationName: "Draft_Survey_Report_Density_Corrected.pdf",
    documentationType: "document",
    documentationUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
    officerMentor: "Chief Officer",
    officerRemarks: "Draft reading technique accurate despite 0.3m swell. Sounding and density hydrometer checks cross-verified.",
    trbReference: "STCW II/1 - Task 4.1: Cargo Operations & Stability",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 4.5,
    location: "Shipside Pilot Ladder & Cargo Office",
    createdAt: "2026-10-01T07:30:00Z",
    updatedAt: "2026-10-01T13:45:00Z"
  },
  {
    id: "cadet-task-p4-002",
    phase: "chief_officer_assist",
    title: "Ballast Water Treatment (BWTS) Operation & D-2 Logbook Documentation",
    description: "Monitored automated UV and electro-chlorination Ballast Water Management System (BWMS) during discharge of 4,200 m³ from Forepeak and Double Bottom Ballast Tanks No. 2 P/S.",
    assistDescription: "Assisted Chief Officer in logging pump runtimes, UV intensity sensor values, salinity, tro-sensors, and completing official entries in the IMO Ballast Water Record Book.",
    date: "2026-10-02",
    status: "Pending Review",
    documentationName: "Ballast_Record_Book_Log_BWMS.jpg",
    documentationType: "checklist",
    documentationUrl: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=600&q=80",
    officerMentor: "Chief Officer",
    officerRemarks: "Pending Chief Officer counter-signature at end of sea watch.",
    trbReference: "STCW II/1 - Task 4.3: Ballast Water Management & BWM Convention",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 3,
    location: "Cargo Control Room (CCR) & Ballast Pump Room",
    createdAt: "2026-10-02T10:00:00Z",
    updatedAt: "2026-10-02T13:00:00Z"
  },
  {
    id: "cadet-task-p4-003",
    phase: "chief_officer_assist",
    title: "Permit to Work (PTW) & Enclosed Space Entry Multi-Gas Atmospheric Test",
    description: "Accompanied Chief Officer for pre-entry inspection of Cargo Hold No. 1 Lower Bilge Wells. Conducted 4-gas atmosphere testing (Oxygen, Lower Explosive Limit, Carbon Monoxide, Hydrogen Sulfide).",
    assistDescription: "Assisted Chief Officer with completing Enclosed Space Entry Checklist, establishing communication links via UHF intrinsically safe radio, and deploying emergency rescue tripod & harness at hatch access trunk.",
    date: "2026-10-05",
    status: "In Progress",
    documentationName: "Enclosed_Space_Permit_Gas_Check.pdf",
    documentationType: "checklist",
    officerMentor: "Chief Officer",
    officerRemarks: "Oxygen verified at 20.9%, 0% LEL, 0 ppm H2S, 0 ppm CO. Sentry posted with resuscitation unit.",
    trbReference: "STCW II/1 - Task 4.4: Safety Management & Enclosed Space Entry",
    cadetName: "Mateo Rossi",
    cadetRank: "Deck Cadet",
    cadetId: "ITA-99214-C",
    hoursSpent: 3.5,
    location: "Cargo Hold No. 1 Trunkway",
    createdAt: "2026-10-02T14:30:00Z",
    updatedAt: "2026-10-02T15:00:00Z"
  }
];
