export const WORLDWIDE_NATIONALITIES = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bulgarian",
  "Burmese",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dutch",
  "Ecuadorean",
  "Egyptian",
  "Emirati",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Guatemalan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kiribati",
  "Korean (South)",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtenstein",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monegasque",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandese",
  "Samoan",
  "Saudi Arabian",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Vanuatuan",
  "Venezuelan",
  "Vietnamese",
  "Yemenite",
  "Zambian",
  "Zimbabwean"
];

export const WORLDWIDE_FLAGS = [
  "Afghanistan 🇦🇫",
  "Albania 🇦🇱",
  "Algeria 🇩🇿",
  "Andorra 🇦🇩",
  "Angola 🇦🇴",
  "Antigua & Barbuda 🇦🇬",
  "Argentina 🇦🇷",
  "Armenia 🇦🇲",
  "Australia 🇦🇺",
  "Austria 🇦🇹",
  "Azerbaijan 🇦🇿",
  "Bahamas 🇧🇸",
  "Bahrain 🇧🇭",
  "Bangladesh 🇧🇩",
  "Barbados 🇧🇧",
  "Belarus 🇧🇾",
  "Belgium 🇧🇪",
  "Belize 🇧🇿",
  "Benin 🇧🇯",
  "Bhutan 🇧🇹",
  "Bolivia 🇧🇴",
  "Bosnia & Herzegovina 🇧🇦",
  "Botswana 🇧🇼",
  "Brazil 🇧🇷",
  "Brunei 🇧🇳",
  "Bulgaria 🇧🇬",
  "Burkina Faso 🇧🇫",
  "Burundi 🇧🇮",
  "Cambodia 🇰🇭",
  "Cameroon 🇨🇲",
  "Canada 🇨🇦",
  "Cape Verde 🇨🇻",
  "Central African Republic 🇨🇫",
  "Chad 🇹🇩",
  "Chile 🇨🇱",
  "China 🇨🇳",
  "Colombia 🇨🇴",
  "Comoros 🇰🇲",
  "Congo 🇨🇬",
  "Costa Rica 🇨🇷",
  "Croatia 🇭🇷",
  "Cuba 🇨🇺",
  "Cyprus 🇨🇾",
  "Czech Republic 🇨🇿",
  "Denmark 🇩🇰",
  "Djibouti 🇩🇯",
  "Dominica 🇩🇲",
  "Dominican Republic 🇩🇴",
  "Ecuador 🇪🇨",
  "Egypt 🇪🇬",
  "El Salvador 🇸🇻",
  "Equatorial Guinea 🇬🇶",
  "Eritrea 🇪🇷",
  "Estonia 🇪🇪",
  "Eswatini 🇸🇿",
  "Ethiopia 🇪🇹",
  "Fiji 🇫🇯",
  "Finland 🇫🇮",
  "France 🇫🇷",
  "Gabon 🇬🇦",
  "Gambia 🇬🇲",
  "Georgia 🇬🇪",
  "Germany 🇩🇪",
  "Ghana 🇬🇭",
  "Greece 🇬🇷",
  "Grenada 🇬🇩",
  "Guatemala 🇬🇹",
  "Guinea 🇬🇳",
  "Guinea-Bissau 🇬🇼",
  "Guyana 🇬🇾",
  "Haiti 🇭🇹",
  "Honduras 🇭🇳",
  "Hungary 🇭🇺",
  "Iceland 🇮🇸",
  "India 🇮🇳",
  "Indonesia 🇮🇩",
  "Iran 🇮🇷",
  "Iraq 🇮🇶",
  "Ireland 🇮🇪",
  "Israel 🇮🇱",
  "Italy 🇮🇹",
  "Ivory Coast 🇨🇮",
  "Jamaica 🇯🇲",
  "Japan 🇯🇵",
  "Jordan 🇯🇴",
  "Kazakhstan 🇰🇿",
  "Kenya 🇰🇪",
  "Kiribati 🇰🇮",
  "Kuwait 🇰🇼",
  "Kyrgyz 🇰🇬",
  "Laos 🇱🇦",
  "Latvia 🇱🇻",
  "Lebanon 🇱🇧",
  "Lesotho 🇱🇸",
  "Liberia 🇱🇷",
  "Libya 🇱🇾",
  "Liechtenstein 🇱🇮",
  "Lithuania 🇱🇹",
  "Luxembourg 🇱🇺",
  "Madagascar 🇲🇬",
  "Malawi 🇲🇼",
  "Malaysia 🇲🇾",
  "Maldives 🇲🇻",
  "Mali 🇲🇱",
  "Malta 🇲🇹",
  "Marshall Islands 🇲🇭",
  "Mauritania 🇲🇷",
  "Mauritius 🇲🇺",
  "Mexico 🇲🇽",
  "Micronesia 🇫🇲",
  "Moldova 🇲🇩",
  "Monaco 🇲🇨",
  "Mongolia 🇲🇳",
  "Montenegro 🇲🇪",
  "Morocco 🇲🇦",
  "Mozambique 🇲🇿",
  "Myanmar 🇲🇲",
  "Namibia 🇳🇦",
  "Nauru 🇳🇷",
  "Nepal 🇳🇵",
  "Netherlands 🇳🇱",
  "New Zealand 🇳🇿",
  "Nicaragua 🇳🇮",
  "Niger 🇳🇪",
  "Nigeria 🇳🇬",
  "North Korea 🇰🇵",
  "North Macedonia 🇲🇰",
  "Norway 🇳🇴",
  "Oman 🇴🇲",
  "Pakistan 🇵🇰",
  "Palau 🇵🇼",
  "Panama 🇵🇦",
  "Papua New Guinea 🇵🇬",
  "Paraguay 🇵🇾",
  "Peru 🇵🇪",
  "Philippines 🇵🇭",
  "Poland 🇵🇱",
  "Portugal 🇵🇹",
  "Qatar 🇶🇦",
  "Romania 🇷🇴",
  "Russia 🇷🇺",
  "Rwanda 🇷🇼",
  "Saint Kitts & Nevis 🇰🇳",
  "Saint Lucia 🇱🇨",
  "Saint Vincent 🇻🇨",
  "Samoa 🇼🇸",
  "San Marino 🇸🇲",
  "Sao Tome & Principe 🇸🇹",
  "Saudi Arabia 🇸🇦",
  "Senegal 🇸🇳",
  "Serbia 🇷🇸",
  "Seychelles 🇸🇨",
  "Sierra Leone 🇸🇱",
  "Singapore 🇸🇬",
  "Slovakia 🇸🇰",
  "Slovenia 🇸🇮",
  "Solomon Islands 🇸🇧",
  "Somalia 🇸🇴",
  "South Africa 🇿🇦",
  "South Korea 🇰🇷",
  "South Sudan 🇸🇸",
  "Spain 🇪🇸",
  "Sri Lanka 🇱🇰",
  "Sudan 🇸🇩",
  "Suriname 🇸🇷",
  "Sweden 🇸🇪",
  "Switzerland 🇨🇭",
  "Syria 🇸🇾",
  "Taiwan 🇹🇼",
  "Tajik 🇹🇯",
  "Tanzania 🇹🇿",
  "Thailand 🇹🇭",
  "Timor-Leste 🇹🇱",
  "Togo 🇹🇬",
  "Tonga 🇹🇴",
  "Trinidad & Tobago 🇹🇹",
  "Tunisia 🇹🇳",
  "Turkey 🇹🇷",
  "Turkmen 🇹🇲",
  "Tuvalu 🇹🇻",
  "Uganda 🇺🇬",
  "Ukraine 🇺🇦",
  "United Arab Emirates 🇦🇪",
  "United Kingdom 🇬🇧",
  "United States 🇺🇸",
  "Uruguay 🇺🇾",
  "Uzbekistan 🇺🇿",
  "Vanuatu 🇻🇺",
  "Vatican City 🇻🇦",
  "Venezuela 🇻🇪",
  "Vietnam 🇻🇳",
  "Yemen 🇾🇪",
  "Zambia 🇿🇲",
  "Zimbabwe 🇿🇼"
];
